### ISSUE TITLE
Many error massages,

### ISSUE THREAD

**Issue by kyuwanchoi** [eurika-kaiser/SINDY-MPC#2]
Hello Dr. Eurika Kaiser,

Currently, I am reading your paper 'Sparse identification of nonlinear dynamics for model predictive control in the low-dat limit'. Your study is very interesting. I like your study and it is very helpful for me.

I downloaded your code and I cannot some of your codes. There are error messages.

I can run: EX_F8_SI_SINDYc.m

I cannot run: EX_F8_SI_DelayDMDc.m

Error using DynamicSystem/lsim (line 84)
When simulating the response to a specific input signal, the input data U must be a
matrix with as many rows as samples in the time vector T, and as many columns as input
channels.

Error in EX_F8_SI_DelayDMDc (line 43)
[xDMDc,~] = lsim(sysmodel_DMDc,Hu',tspan(1:end-1),x(1,:)'-xmean');

I cannot run: EX_F8_SI_NARX.m

I need your help about your code.

**Comment by Jkaplan1123** [comment]
If you look at the size of Hu and of tspan, you will see they are both 1D vectors of the same length. For the purpose of this explanation, lets say they are of length n. When you run: 

`[xDMDc,~] = lsim(sysmodel_DMDc,Hu',tspan(1:end-1),x(1,:)'-xmean');` 

then you are feeding in all n terms of Hu but only the first n-1 terms of tspan. This causes the error message you quote. If you change tspan(1:end-1) to tspan(1:end), then you have an error in the next line because it causes your matrix dimensions to disagree. The fix to this is to only feed in the first (n-1) terms of Hu. This can be done multiple ways. The simplest is to replace Hu' with Hu(1:end-1) in the `lsim` command above.

As for your error with EX_F8_SI_NARX.m, I am also having issues with that and cannot help.

**Comment by eurika-kaiser** [comment]
Thanks for pointing this out! The error has been fixed.

There was a file missing unfortunately, which has been added.
If you would like to learn the NARX model for the F8 on ensemble training data, you need to run the file EX_F8_SI_NARX_Ensemble.m.

**Comment by kyuwanchoi** [comment]
Hi Eurika,

Thanks a lot for helping me. I are super smart!

Best,
Kyu
